//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مکان اقدام دارای گزارشاتی میباشد و حذف آن امکان پذیر نیست.
        /// </summary>
        public static string ActionPlaceHasTicketError {
            get {
                return ResourceManager.GetString("ActionPlaceHasTicketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مکان اقدامی وجود ندارد.
        /// </summary>
        public static string ActionPlaceIsNull {
            get {
                return ResourceManager.GetString("ActionPlaceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مکان اقدام اجباری میباشد.
        /// </summary>
        public static string ActionPlaceNameRequired {
            get {
                return ResourceManager.GetString("ActionPlaceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مکان اقدام مورد نظر یافت نشد.
        /// </summary>
        public static string ActionPlaceNotFound {
            get {
                return ResourceManager.GetString("ActionPlaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ مکان اقدامی انتخاب نشده است.
        /// </summary>
        public static string ActionPlaceSelectError {
            get {
                return ResourceManager.GetString("ActionPlaceSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نوع اقدام دارای گزارشاتی میباشد و حذف آن امکان پذیر یست.
        /// </summary>
        public static string ActionTypeHasTicketError {
            get {
                return ResourceManager.GetString("ActionTypeHasTicketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اقدامی وجود ندارد.
        /// </summary>
        public static string ActionTypeIsNull {
            get {
                return ResourceManager.GetString("ActionTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نوع اقدام اجباری میباشد.
        /// </summary>
        public static string ActionTypeNameRequired {
            get {
                return ResourceManager.GetString("ActionTypeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اقدام یافت نشد.
        /// </summary>
        public static string ActionTypeNotFound {
            get {
                return ResourceManager.GetString("ActionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نوع اقدام را وارد کنید.
        /// </summary>
        public static string ActionTypeSelectedError {
            get {
                return ResourceManager.GetString("ActionTypeSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا آلبوم مربوطه را انتخاب نمایید !.
        /// </summary>
        public static string AlbumSelect {
            get {
                return ResourceManager.GetString("AlbumSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تیکت شما با شماره {0}، از حالت &apos;{1}&apos; به حالت &apos;{2}&apos;، توسط ( {3} ) تغییر یافت..
        /// </summary>
        public static string AnswerChangeStatusTicket {
            get {
                return ResourceManager.GetString("AnswerChangeStatusTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخی برای این ارجاع یافت نشد.
        /// </summary>
        public static string AnswerForThisReferenceNotFound {
            get {
                return ResourceManager.GetString("AnswerForThisReferenceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا فایل با فرمت .zip ,  .pdf , .rtf , .doc ,یا  .docx وارد نمایید !.
        /// </summary>
        public static string AttachFormat {
            get {
                return ResourceManager.GetString("AttachFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان موضوع اجباری میباشد.
        /// </summary>
        public static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوعی یافت نشد.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ موضوعی انتخاب نشده است.
        /// </summary>
        public static string CategorySelectedError {
            get {
                return ResourceManager.GetString("CategorySelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت مورد نظر با موفقیت حذف شد.
        /// </summary>
        public static string CompanyIsDeleted {
            get {
                return ResourceManager.GetString("CompanyIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت تاریخ شروع را چک کنید.
        /// </summary>
        public static string CreateDateFormat {
            get {
                return ResourceManager.GetString("CreateDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلت تاریخ شرکت شما به اتمام رسیده است لطفا با شرکت هماهنگ کنید.
        /// </summary>
        public static string CustomerExpiredError {
            get {
                return ResourceManager.GetString("CustomerExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای حذف شرکت مورد نظر ابتدا ارتباطات گروه ها را چک کنید.
        /// </summary>
        public static string CustomerHasMappingError {
            get {
                return ResourceManager.GetString("CustomerHasMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای حذف یک شرکت ابتدا پروژه های آنرا حذف کنید.
        /// </summary>
        public static string CustomerHasprojectError {
            get {
                return ResourceManager.GetString("CustomerHasprojectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای حذف یک شرکت ابتدا کاربران آن را حذف کنید.
        /// </summary>
        public static string CustomerHasUserError {
            get {
                return ResourceManager.GetString("CustomerHasUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت مورد نظر فعال نیست لطفا با شرکت هماهنگ فرمایید.
        /// </summary>
        public static string CustomerNotActiveError {
            get {
                return ResourceManager.GetString("CustomerNotActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکتی وجود ندارد.
        /// </summary>
        public static string CustomerNotExist {
            get {
                return ResourceManager.GetString("CustomerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ شرکتی یافت نشد.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری / شرکت وجود ندارد.
        /// </summary>
        public static string CustomerOrCompanyIsNull {
            get {
                return ResourceManager.GetString("CustomerOrCompanyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ شرکتی انتخاب نشده است.
        /// </summary>
        public static string CustomerSelectedError {
            get {
                return ResourceManager.GetString("CustomerSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تداخل تاریخ وجود دارد.
        /// </summary>
        public static string DateConflictError {
            get {
                return ResourceManager.GetString("DateConflictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت تاریخ نامعتبر !.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انجام کار وارد نشده است.
        /// </summary>
        public static string DateOfOperation {
            get {
                return ResourceManager.GetString("DateOfOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات / شرح اجباری میباشد.
        /// </summary>
        public static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا فیلدهای عددی را صحیح وارد نمایید.
        /// </summary>
        public static string DigitFormat {
            get {
                return ResourceManager.GetString("DigitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ذخیره تغییرات !.
        /// </summary>
        public static string EditError {
            get {
                return ResourceManager.GetString("EditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره تغییرات با موفقیت انجام شد ..
        /// </summary>
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت پست الکترونیک را صحیح وارد نمایید.
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد از تکمیل اطلاعات خواسته شده و انتخاب دریافت کننده مناسب  دکمه ارسال را کلیک کنید.
        /// </summary>
        public static string EmailHelp {
            get {
                return ResourceManager.GetString("EmailHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عنوان مورد نظر را وارد نمائید!.
        /// </summary>
        public static string EmpttyTitle {
            get {
                return ResourceManager.GetString("EmpttyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما هیچ پاسخی برای سوال خود وارد نکرده اید !.
        /// </summary>
        public static string EmptyAnswer {
            get {
                return ResourceManager.GetString("EmptyAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا پست الکترونیک خود را وارد نمایید !.
        /// </summary>
        public static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا رشته را وارد نمایید !.
        /// </summary>
        public static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا فایل مورد نظر را انتخاب نمایید !.
        /// </summary>
        public static string EmptyFile {
            get {
                return ResourceManager.GetString("EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتفاع را وارد کنید!.
        /// </summary>
        public static string Emptyheight {
            get {
                return ResourceManager.GetString("Emptyheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا درس را وارد نمایید !.
        /// </summary>
        public static string EmptyLesson {
            get {
                return ResourceManager.GetString("EmptyLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا جهت ارسال نظر گزینه ای را انتخاب نمایید! .
        /// </summary>
        public static string EmptyPoll {
            get {
                return ResourceManager.GetString("EmptyPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا سوال خود را وارد نمایید !.
        /// </summary>
        public static string EmptyQuestion {
            get {
                return ResourceManager.GetString("EmptyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام قسمت را وارد نمایید !.
        /// </summary>
        public static string EmptySection {
            get {
                return ResourceManager.GetString("EmptySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا متن را وارد نمایید !.
        /// </summary>
        public static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عنوان را وارد نمایید !.
        /// </summary>
        public static string EmptyTitle {
            get {
                return ResourceManager.GetString("EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا دانشگاه را وارد نمایید !.
        /// </summary>
        public static string EmptyUniversity {
            get {
                return ResourceManager.GetString("EmptyUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض را وارد کنید!.
        /// </summary>
        public static string EmptyWidth {
            get {
                return ResourceManager.GetString("EmptyWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و یا رمز عبور اشتباه وارد شده است لطفا دوباره تلاش کنید !.
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت تاریخ پایان را چک کنید.
        /// </summary>
        public static string ExpireDateFormat {
            get {
                return ResourceManager.GetString("ExpireDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام خانوادگی را وارد نمایید.
        /// </summary>
        public static string FamilyEmpty {
            get {
                return ResourceManager.GetString("FamilyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع پایگاه دانش را انتخاب کنید.
        /// </summary>
        public static string FAQCategorySelectedError {
            get {
                return ResourceManager.GetString("FAQCategorySelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ مطلبی در پایگاه دانش ثبت نشده است.
        /// </summary>
        public static string FAQIsNull {
            get {
                return ResourceManager.GetString("FAQIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایگاه دانش مورد نظر یافت نشد.
        /// </summary>
        public static string FAQNotFoundError {
            get {
                return ResourceManager.GetString("FAQNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر حجم مجاز برای آپلود 1 مگابایت میباشد.
        /// </summary>
        public static string File1MBError {
            get {
                return ResourceManager.GetString("File1MBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا فایل را انتخاب نمایید!.
        /// </summary>
        public static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز خطا، لطفا فایل جدیدی را تست کنید.
        /// </summary>
        public static string FileError_SelectNewFile {
            get {
                return ResourceManager.GetString("FileError_SelectNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسوند فایل مورد نظر مورد تایید نمیباشد.
        /// </summary>
        public static string FileExtensionError {
            get {
                return ResourceManager.GetString("FileExtensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل مورد نظر را انتخاب کنید.
        /// </summary>
        public static string FileSelect {
            get {
                return ResourceManager.GetString("FileSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر یافت نشد.
        /// </summary>
        public static string FindUserIdFailed {
            get {
                return ResourceManager.GetString("FindUserIdFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما می بایست فایلی با فرمت gif وارد کنید !.
        /// </summary>
        public static string GifOnly {
            get {
                return ResourceManager.GetString("GifOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا گروه را وارد کنید.
        /// </summary>
        public static string GroupEmpty {
            get {
                return ResourceManager.GetString("GroupEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای حذف یک گروه ابتدا ارتباطات آن گروه را حذف کنید.
        /// </summary>
        public static string GroupHasMappingError {
            get {
                return ResourceManager.GetString("GroupHasMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف گروهی که شامل تعدادی کاربر میباشد نیست.
        /// </summary>
        public static string GroupHasUserError {
            get {
                return ResourceManager.GetString("GroupHasUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروهی وجود ندارد.
        /// </summary>
        public static string GroupIsNull {
            get {
                return ResourceManager.GetString("GroupIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروهی وجود ندارد.
        /// </summary>
        public static string GroupNotExist {
            get {
                return ResourceManager.GetString("GroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه مورد نظر یافت نشد.
        /// </summary>
        public static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابطه ای بین گروه ها وجود ندارد.
        /// </summary>
        public static string GroupRelationIsNull {
            get {
                return ResourceManager.GetString("GroupRelationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروهی انتخاب نشده است.
        /// </summary>
        public static string GroupSelectError {
            get {
                return ResourceManager.GetString("GroupSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  شما می بایست فایلی با فرمت gif, jpg , jpeg ویا bmp وارد کنید !.
        /// </summary>
        public static string ImgFormat {
            get {
                return ResourceManager.GetString("ImgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز فایل بزرگ می باشد.
        /// </summary>
        public static string ImgSize {
            get {
                return ResourceManager.GetString("ImgSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم مورد نظر یافت نشد.
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی اجباری میباشد.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت لینک وارد شده نامعتبر است !.
        /// </summary>
        public static string LinkFormat {
            get {
                return ResourceManager.GetString("LinkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کمی صبر کنید.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و یا رمز عبور اشتباه وارد شده است !.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج از حساب کاربری.
        /// </summary>
        public static string LogOutFromAccount {
            get {
                return ResourceManager.GetString("LogOutFromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ مسیری برای ارجاع این تیکت یافت نشد.
        /// </summary>
        public static string MappingNotFound {
            get {
                return ResourceManager.GetString("MappingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت مورد نظر نمیتواند به شرکت مالک ارجاع شود.
        /// </summary>
        public static string MappingOwnerCompanyNotFound {
            get {
                return ResourceManager.GetString("MappingOwnerCompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر حجم فایل ها 1 مگابایت.
        /// </summary>
        public static string MaximumSize1MB {
            get {
                return ResourceManager.GetString("MaximumSize1MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز فایل می بایست کمتر از 500000 بایت باشد !.
        /// </summary>
        public static string MaxSize500000 {
            get {
                return ResourceManager.GetString("MaxSize500000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا پیام خود را وارد نمایید!.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیشترین حد ارسال تیکت نمیتواند 0 باشد.
        /// </summary>
        public static string MinTicketCountError {
            get {
                return ResourceManager.GetString("MinTicketCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه را بررسی کنید.
        /// </summary>
        public static string MobileError {
            get {
                return ResourceManager.GetString("MobileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اجباری است.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی را چک کنید.
        /// </summary>
        public static string NationalCodeError {
            get {
                return ResourceManager.GetString("NationalCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما به گروه مدیریت دسترسی ندارید.
        /// </summary>
        public static string NotAccessToAdminGroup {
            get {
                return ResourceManager.GetString("NotAccessToAdminGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدودیت در سطح دسترسی، لطفا با شرکت هماهنگ کنید.
        /// </summary>
        public static string NotAccessToPageConnectToCompany {
            get {
                return ResourceManager.GetString("NotAccessToPageConnectToCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد وارد شده در محدوده مجاز نمی باشد.
        /// </summary>
        public static string NumberRange {
            get {
                return ResourceManager.GetString("NumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و تکرار رمز عبور یکسان نیست.
        /// </summary>
        public static string Password_PasswordConfirmError {
            get {
                return ResourceManager.GetString("Password_PasswordConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور اجباری است.
        /// </summary>
        public static string PasswordConfirmRequired {
            get {
                return ResourceManager.GetString("PasswordConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزعبور اجباری است.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن را بررسی کنید.
        /// </summary>
        public static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای استفاده از سایت ابتدا وارد حساب کاربری خود شوید.
        /// </summary>
        public static string PleaseLoginInSite {
            get {
                return ResourceManager.GetString("PleaseLoginInSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا سمت را وارد نمایید !.
        /// </summary>
        public static string PostEmpty {
            get {
                return ResourceManager.GetString("PostEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای حذف پروژه ابتدا گروه های مورد نظر را حذف کنید.
        /// </summary>
        public static string ProjectHasGroup {
            get {
                return ResourceManager.GetString("ProjectHasGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای حذف پروژه ابتدا ارتباطات گروه های آنرا حذف کنید.
        /// </summary>
        public static string ProjectHasMapping {
            get {
                return ResourceManager.GetString("ProjectHasMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای حذف یک پروژه ابتدا زیر سیستم های آنرا حدف کنید.
        /// </summary>
        public static string ProjectHasSubSystemError {
            get {
                return ResourceManager.GetString("ProjectHasSubSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه ای وجود ندارد.
        /// </summary>
        public static string ProjectIsNull {
            get {
                return ResourceManager.GetString("ProjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پروژه اجباری میباشد.
        /// </summary>
        public static string ProjectNameRequired {
            get {
                return ResourceManager.GetString("ProjectNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ پروژه ای وجود ندارد.
        /// </summary>
        public static string ProjectNotExist {
            get {
                return ResourceManager.GetString("ProjectNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه مورد نظر یافت نشد.
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ پروژه ای انتخاب نشده است.
        /// </summary>
        public static string ProjectSelectedError {
            get {
                return ResourceManager.GetString("ProjectSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مایل به حذف رکورد مورد نظر هستید؟.
        /// </summary>
        public static string QuestionDelete {
            get {
                return ResourceManager.GetString("QuestionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا متن پرسش را وارد کنید.
        /// </summary>
        public static string QuestionEmpty {
            get {
                return ResourceManager.GetString("QuestionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مایل به ثبت تغییرات هستید؟.
        /// </summary>
        public static string QuestionUpdate {
            get {
                return ResourceManager.GetString("QuestionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان صف ارسال تیکت شما به شرکت پر شده است لطفا با شرکت هماهنگ کنین.
        /// </summary>
        public static string QueueSentTicketIsFull {
            get {
                return ResourceManager.GetString("QueueSentTicketIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عددی در محدوده 0 تا 1000 وارد نمایید !.
        /// </summary>
        public static string RangNo1000 {
            get {
                return ResourceManager.GetString("RangNo1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عددی بین 0 تا 10 را وارد نمایید !.
        /// </summary>
        public static string RangUnit {
            get {
                return ResourceManager.GetString("RangUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارجاع با موفقیت انجام شد.
        /// </summary>
        public static string ReferenceIsSeccess {
            get {
                return ResourceManager.GetString("ReferenceIsSeccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارجاع کردن و ثبت پاسخ.
        /// </summary>
        public static string ReferenceTicketWithSaveAnswer {
            get {
                return ResourceManager.GetString("ReferenceTicketWithSaveAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش مورد نظر با موفقیت حذف شد.
        /// </summary>
        public static string ReportIsDeleted {
            get {
                return ResourceManager.GetString("ReportIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارشی وجود ندارد.
        /// </summary>
        public static string ReportIsNull {
            get {
                return ResourceManager.GetString("ReportIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش مورد نظر یافت نشد.
        /// </summary>
        public static string ReportNotFound {
            get {
                return ResourceManager.GetString("ReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما نامعتبر میباشد.
        /// </summary>
        public static string RequestNotValid {
            get {
                return ResourceManager.GetString("RequestNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نقش اجباری میباشد.
        /// </summary>
        public static string RoleNameRequired {
            get {
                return ResourceManager.GetString("RoleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشی وجود ندارد.
        /// </summary>
        public static string RoleNotExist {
            get {
                return ResourceManager.GetString("RoleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش مود نظر یافت نشد.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک نقش را انتخاب کنید.
        /// </summary>
        public static string RoleSelectedError {
            get {
                return ResourceManager.GetString("RoleSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان فارسی نقش اجباری میباشد.
        /// </summary>
        public static string RoleTitleRequired {
            get {
                return ResourceManager.GetString("RoleTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ذخیره اطلاعات !.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره اطلاعات با موفقیت انجام شد ..
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت به عنوان گزارش.
        /// </summary>
        public static string SaveTicketToReport {
            get {
                return ResourceManager.GetString("SaveTicketToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت مشاده نکردن مورد خود میتوانید تیکت ثبت کنید.
        /// </summary>
        public static string SaveTicketWhenCountFAQZiro {
            get {
                return ResourceManager.GetString("SaveTicketWhenCountFAQZiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در پایگاه دانش.
        /// </summary>
        public static string SearchInFAQ {
            get {
                return ResourceManager.GetString("SearchInFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتیجه ای یافت نشد.
        /// </summary>
        public static string SearchResultIsNull {
            get {
                return ResourceManager.GetString("SearchResultIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب همه.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک موضوع را انتخاب کنید.
        /// </summary>
        public static string SelectedCategoryError {
            get {
                return ResourceManager.GetString("SelectedCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک زیر سیستم انتخاب کنید.
        /// </summary>
        public static string SelectedSubSystemError {
            get {
                return ResourceManager.GetString("SelectedSubSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک اولویت را انتخاب کنید.
        /// </summary>
        public static string SelectedUserPriotryError {
            get {
                return ResourceManager.GetString("SelectedUserPriotryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب کنید.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب زیر سیستم یا پروژه اجباری میباشد.
        /// </summary>
        public static string SelectSubSystemOrProjectError {
            get {
                return ResourceManager.GetString("SelectSubSystemOrProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از بین افراد مورد های مورد نظر را انتخاب کنید.
        /// </summary>
        public static string SelectTrueOptionUsers {
            get {
                return ResourceManager.GetString("SelectTrueOptionUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب گروه یا یک شخص در یک گروه اجباری میباشد.
        /// </summary>
        public static string SelectUserGroupProjectOrUserFromProjectSelected {
            get {
                return ResourceManager.GetString("SelectUserGroupProjectOrUserFromProjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در پاسخ به درخواست.
        /// </summary>
        public static string ServerReqestError {
            get {
                return ResourceManager.GetString("ServerReqestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش پروفایل.
        /// </summary>
        public static string ShowProfilePage {
            get {
                return ResourceManager.GetString("ShowProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عنوان سایت را وارد نمایید.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تیکت مورد نظر یافت نشد.
        /// </summary>
        public static string StatusTicketNotFound {
            get {
                return ResourceManager.GetString("StatusTicketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف زیر سیستم هایی که تیکت برایشان ثبت شده است نیست.
        /// </summary>
        public static string SubSystemHasTicketError {
            get {
                return ResourceManager.GetString("SubSystemHasTicketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر سیستمی وجود ندارد.
        /// </summary>
        public static string SubSystemIsNull {
            get {
                return ResourceManager.GetString("SubSystemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام زیرسیستم اجباری میباشد.
        /// </summary>
        public static string SubSystemNameRequired {
            get {
                return ResourceManager.GetString("SubSystemNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر سیستمی وجود ندارد.
        /// </summary>
        public static string SubSystemNotExist {
            get {
                return ResourceManager.GetString("SubSystemNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر سیستمی یافت نشد.
        /// </summary>
        public static string SubSystemNotFound {
            get {
                return ResourceManager.GetString("SubSystemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ زیرسیستمی انتخاب نشده است.
        /// </summary>
        public static string SubsystemSelectedError {
            get {
                return ResourceManager.GetString("SubsystemSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت وارد حساب کاربری خود شدید.
        /// </summary>
        public static string SuccessLoginMessage {
            get {
                return ResourceManager.GetString("SuccessLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه مدیریت سازمان یافت نشد / بروز خطا در سیستم.
        /// </summary>
        public static string SupportManagmentGroupInCustomerNotFound {
            get {
                return ResourceManager.GetString("SupportManagmentGroupInCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز خطا در سیستم.
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز خطا در سیستم، مجدد تلاش کنید.
        /// </summary>
        public static string SystemError_TryAgain {
            get {
                return ResourceManager.GetString("SystemError_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز خطا در سیستم / مجدد وارد حساب کاربری شوید و تلاش کنید.
        /// </summary>
        public static string SystemErrorReLogin {
            get {
                return ResourceManager.GetString("SystemErrorReLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا فایل با فرمت  .pdf  , .doc ,یا  .docx وارد نمایید !.
        /// </summary>
        public static string TextFormat {
            get {
                return ResourceManager.GetString("TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مورد نظر در سامانه وجود دارد..
        /// </summary>
        public static string ThisNameIsExist {
            get {
                return ResourceManager.GetString("ThisNameIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این ارتباط وجود دارد.
        /// </summary>
        public static string ThisRelationIsExist {
            get {
                return ResourceManager.GetString("ThisRelationIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت مورد نظر یافت نشد.
        /// </summary>
        public static string TicketNotFound {
            get {
                return ResourceManager.GetString("TicketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ مسیری برای ارجاع تیکت مورد نظر با پروژه و زیر سیستم مد نظر شما یافت نشد لطفا با تیم پشتیبانی هماهنگ کنید.
        /// </summary>
        public static string TicketReferenceForTicketNotSet {
            get {
                return ResourceManager.GetString("TicketReferenceForTicketNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشفرض ارجاعاتی وجود ندارد.
        /// </summary>
        public static string TicketReferenceNotExist {
            get {
                return ResourceManager.GetString("TicketReferenceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تیکت اجباری میباشد.
        /// </summary>
        public static string TicketTypeIsRequired {
            get {
                return ResourceManager.GetString("TicketTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تیکت مورد نظر یافت نشد.
        /// </summary>
        public static string TicketTypeNotFound {
            get {
                return ResourceManager.GetString("TicketTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان انجام کار وارد نشده است.
        /// </summary>
        public static string TimeOfOperation {
            get {
                return ResourceManager.GetString("TimeOfOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان اجباری است.
        /// </summary>
        public static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری های درحال استفاده.
        /// </summary>
        public static string UseCustomers {
            get {
                return ResourceManager.GetString("UseCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه های درحال استفاده.
        /// </summary>
        public static string Useprojects {
            get {
                return ResourceManager.GetString("Useprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران افزوده شده.
        /// </summary>
        public static string UserAddedInListGroup {
            get {
                return ResourceManager.GetString("UserAddedInListGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر در این گروه وجود دارد.
        /// </summary>
        public static string UserExistInGroup {
            get {
                return ResourceManager.GetString("UserExistInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت ورود با این حساب کاربری با شرکت تماس بگیرید.
        /// </summary>
        public static string UserExpiredError {
            get {
                return ResourceManager.GetString("UserExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ ارتباطی برای شخص و گروه مورد نظر یافت نشد.
        /// </summary>
        public static string UserGroupProjectNotFound {
            get {
                return ResourceManager.GetString("UserGroupProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک شخص با گروه مشخص شده انتخاب کنید.
        /// </summary>
        public static string UserGroupProjectSelectError {
            get {
                return ResourceManager.GetString("UserGroupProjectSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف افرادی که تیکت ارسال کرده اند نیست.
        /// </summary>
        public static string UserHasTicketError {
            get {
                return ResourceManager.GetString("UserHasTicketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری مورد نظر تکراری است.
        /// </summary>
        public static string UserNameIsExistError {
            get {
                return ResourceManager.GetString("UserNameIsExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری اجباری است.
        /// </summary>
        public static string UserNameRequied {
            get {
                return ResourceManager.GetString("UserNameRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر فعال نمیباشد.
        /// </summary>
        public static string UserNotActiveError {
            get {
                return ResourceManager.GetString("UserNotActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری وجود ندارد.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولویت کاربر اجباری میباشد.
        /// </summary>
        public static string UserPriotryIsRequired {
            get {
                return ResourceManager.GetString("UserPriotryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولیت کاربر مورد نظر یافت نشد.
        /// </summary>
        public static string UserPriotryNotFound {
            get {
                return ResourceManager.GetString("UserPriotryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولویت کاربر را انتخاب کنید.
        /// </summary>
        public static string UserPriotryNotSelected {
            get {
                return ResourceManager.GetString("UserPriotryNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران شرکت مورد نظر.
        /// </summary>
        public static string UserSelectedCustomer {
            get {
                return ResourceManager.GetString("UserSelectedCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف کاربری که در صفحه پیش فرض ارجاعات انتخاب شده است نمیباشد.
        /// </summary>
        public static string UserWithGroupHasTicketReferenceError {
            get {
                return ResourceManager.GetString("UserWithGroupHasTicketReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صفحه اصلی مشاهده شود.
        /// </summary>
        public static string ViewOnTheMainPage {
            get {
                return ResourceManager.GetString("ViewOnTheMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ شما به تیکت.
        /// </summary>
        public static string YourAnswerToTicket {
            get {
                return ResourceManager.GetString("YourAnswerToTicket", resourceCulture);
            }
        }
    }
}
