//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.InitialData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.InitialData.Pages", typeof(Pages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل اقدامات.
        /// </summary>
        public static string ActionPlace {
            get {
                return ResourceManager.GetString("ActionPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اقدامات.
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری / شرکت.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه های مشترکین.
        /// </summary>
        public static string CustomerProject {
            get {
                return ResourceManager.GetString("CustomerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایگاه دانش.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوعات پایگاه دانش.
        /// </summary>
        public static string FAQCategories {
            get {
                return ResourceManager.GetString("FAQCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تولید پایگاه دانش.
        /// </summary>
        public static string FAQCreate {
            get {
                return ResourceManager.GetString("FAQCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری فایل ها.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت گروه ها.
        /// </summary>
        public static string GroupManagment {
            get {
                return ResourceManager.GetString("GroupManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباطات گروه ها.
        /// </summary>
        public static string GroupRelations {
            get {
                return ResourceManager.GetString("GroupRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود کاربران.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت پروژه ها.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت های دریافتی.
        /// </summary>
        public static string ReceivedTickets {
            get {
                return ResourceManager.GetString("ReceivedTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارشات.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت تیکت جدید.
        /// </summary>
        public static string SaveNewTicket {
            get {
                return ResourceManager.GetString("SaveNewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش تیکت - پاسخ دهی و ارجاع.
        /// </summary>
        public static string ShowtTicket {
            get {
                return ResourceManager.GetString("ShowtTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت زیرسیستم ها.
        /// </summary>
        public static string SubSystem {
            get {
                return ResourceManager.GetString("SubSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت.
        /// </summary>
        public static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشفرض ارجاعات.
        /// </summary>
        public static string TicketReference {
            get {
                return ResourceManager.GetString("TicketReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روند تیکت ها.
        /// </summary>
        public static string TicketTrending {
            get {
                return ResourceManager.GetString("TicketTrending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
